import type { Metadata } from "next";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/_features/App-sidebar";
import { Button } from "@/components/ui/button";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <header className="flex justify-between items-center p-4 gap-4 h-16 border-b border-b-[#E4E4E7] z-50 bg-white sticky top-0">
            <p className="text-black font-gip text-[24px] font-semibold leading-normal tracking-[-0.528px]">
              Quiz app
            </p>
            <div>
              <SignedOut>
                <SignInButton>
                  <Button
                    variant="outline"
                    className="rounded-full font-medium text-sm h-10 px-4 cursor-pointer sm:px-5 sm:h-12 mr-3"
                  >
                    Sign in
                  </Button>
                </SignInButton>
                <SignUpButton>
                  <button className="bg-[#6c47ff] text-white rounded-full font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 cursor-pointer">
                    Sign Up
                  </button>
                </SignUpButton>
              </SignedOut>
              <SignedIn>
                <UserButton />
              </SignedIn>
            </div>
          </header>
          <SidebarProvider>
            <AppSidebar />
            <main className="flex-1 min-h-screen flex bg-zinc-50 w-full">
              <div className="px-4 pt-4 pb-0 self-stretch border-r border-r-zinc-200 bg-white w-fit h-full">
                <SidebarTrigger />
              </div>
              {children}
            </main>
          </SidebarProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
